In [1]:
import numpy as np

In [6]:
theta = 4
theta = np.asarray(theta)
type(theta)

numpy.ndarray

In [8]:
a =[[1,2],[3,4],[5,6]]
a = np.array(a)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
b = np.random.randint(1,6,(2, 3))#随机生成一个元素从1到5（前包含后不包含）、两行三列的np数组
print(b)

[[5 1 5]
 [5 5 4]]


In [15]:
# 查看形状
print(a.shape)
print(b.shape)

(3, 2)
(2, 3)


In [21]:
# 多种变形
# 填写元素个数，变成一维
print(a.reshape(6))
b.reshape(6)

[1 2 3 4 5 6]


array([5, 1, 5, 5, 5, 4])

In [22]:
# 只给行数n，numpy根据给出的行数，自行计算（列参数为-1，注意元素总的个数要能被n整除）
# 或者是在不知道转换之后a的列数应该是多少的情况下使用
a.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
b.reshape(6,-1)

array([[5],
       [1],
       [5],
       [5],
       [5],
       [4]])

In [25]:
# 只给列数。同理。在不知道a的行数的情况下也可以使用。
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [26]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
a.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b.reshape(-1,6)

array([[5, 1, 5, 5, 5, 4]])

In [29]:
print(b)

[[5 1 5]
 [5 5 4]]


In [40]:
# projuection
base_face = np.array([[1,1,1],
                    [1,-1,1],
                    [-1,-1,1],
                    [-1,1,1],
                    [1,1,1]], dtype=float)
print(base_face)
base_face.reshape(-1,5)

[[ 1.  1.  1.]
 [ 1. -1.  1.]
 [-1. -1.  1.]
 [-1.  1.  1.]
 [ 1.  1.  1.]]


array([[ 1.,  1.,  1.,  1., -1.],
       [ 1., -1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [ ]:
# x = x.new_ones(5, 3, dtype=torch.double)
# x = torch.rand(5, 3)
# 操作

# 操作有多种语法。

# 我们将看一下加法运算。

# 加法1:

# In [9]:
# y = torch.rand(5, 3)
# print(x + y)
# tensor([[ 0.7808, -1.4388,  0.3151],
#         [-0.0076,  1.0716, -0.8465],
#         [-0.8175,  0.3625, -0.2005],
#         [ 0.2435,  0.8512,  0.7142],
#         [ 1.4737, -0.8545,  2.4833]])
# 加法2

# In [10]:
# print(torch.add(x, y))
# tensor([[ 0.7808, -1.4388,  0.3151],
#         [-0.0076,  1.0716, -0.8465],
#         [-0.8175,  0.3625, -0.2005],
#         [ 0.2435,  0.8512,  0.7142],
#         [ 1.4737, -0.8545,  2.4833]])
# 提供输出tensor作为参数